apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoendpoint
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demoendpoint
  template:
    metadata:
      labels:
        app: demoendpoint
    spec:
      containers:
      - name: demoendpoint
        image: worming/demoendpoint:v1.0
        ports:
        - containerPort: 9090
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1